# Generated by Django 3.2.7 on 2021-10-24 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTitle', models.CharField(help_text='Post başlığı bilgisi.', max_length=100, verbose_name='Post Başlığı')),
                ('postContent', models.TextField(max_length=500, verbose_name='Post İçeriği')),
                ('postDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('articleImage', models.FileField(blank=True, null=True, upload_to='')),
                ('postAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
