# Generated by Django 3.2.7 on 2021-10-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id'], 'verbose_name_plural': 'Gönderiler'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='articleImage',
            new_name='postImage',
        ),
    ]
