# Generated by Django 3.2.7 on 2021-11-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
